NOSTDINC_FLAGS := \
	-I$(M)/include/ \
	-I$(M)/include/uapi \
	-I$(M)/include/drm \
	-include $(M)/include/linux/compat-2.6.h \
	$(CFLAGS)

obj-y += compat/

obj-$(CPTCFG_CFG80211) += net/wireless/
obj-$(CPTCFG_MAC80211) += net/mac80211/
obj-$(CPTCFG_RFKILL) += net/rfkill/
obj-$(CPTCFG_WLAN) += drivers/net/wireless/
